# Generated by Django 4.2.9 on 2024-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bedrijfsnaam", models.CharField(max_length=255)),
                (
                    "type_bedrijf",
                    models.CharField(
                        choices=[("Commerciëel", "Commerciëel"), ("non-profit", "non-profit")],
                        max_length=255,
                    ),
                ),
                ("website", models.TextField()),
                ("beschrijving", models.TextField()),
                ("contactpersoon", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("telefoonnummer", models.CharField(max_length=255)),
                ("Overige_details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "organization",
            },
        ),
    ]
