# Generated by Django 4.2.9 on 2024-02-06 21:52

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="Overige_details",
            field=models.TextField(null=True),
        ),
    ]
