# Generated by Django 4.2.9 on 2024-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organization_overige_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titel", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nieuw", "nieuw"),
                            ("goedgekeurd", "goedgekeurd"),
                            ("afgekeurd", "afgekeurd"),
                            ("gesloten", "gesloten"),
                        ],
                        max_length=255,
                    ),
                ),
                ("beschikbaar", models.BooleanField(default=0, max_length=1)),
                ("beschrijving", models.TextField()),
                ("datum_vanaf", models.DateTimeField()),
                ("datum_tot", models.DateTimeField()),
                (
                    "type_onderzoek",
                    models.CharField(
                        choices=[
                            ("locatie", "locatie"),
                            ("telefonisch", "telefonisch"),
                            ("online", "online"),
                        ],
                        max_length=255,
                    ),
                ),
                ("locatie", models.TextField(null=True)),
                ("met_beloning", models.BooleanField(default=0, max_length=1)),
                ("beloning", models.TextField(null=True)),
                ("doelgroep_leeftijd_van", models.IntegerField()),
                ("doelgroep_leeftijd_tot", models.IntegerField()),
                (
                    "doelgroep_beperking",
                    models.CharField(
                        choices=[
                            (
                                "Auditieve beperkingen",
                                (
                                    ("Doof", "Doof"),
                                    ("Slechthorend", "Slechthorend"),
                                    ("Doofblind", "Doofblind"),
                                ),
                            ),
                            (
                                "Visuele beperkingen",
                                (
                                    ("Blind", "Blind"),
                                    ("Slechtziend", "Slechtziend"),
                                    ("Kleurenblind", "Kleurenblind"),
                                    ("Doofblind", "Doofblind"),
                                ),
                            ),
                            (
                                "Motorische / lichamelijke beperkingen",
                                (
                                    ("Amputatie en mismaaktheid", "Amputatie en mismaaktheid"),
                                    ("Artritus", "Artritus"),
                                    ("Fibromyalgie", "Fibromyalgie"),
                                    ("Reuma", "Reuma"),
                                    ("Verminderde handvaardigheid", "Verminderde handvaardigheid"),
                                    ("Spierdystrofie", "Spierdystrofie"),
                                    ("RSI", "RSI"),
                                    ("Tremor en Spasmen", "Tremor en Spasmen"),
                                    ("Quadriplegie of tetraplegie", " Quadriplegie of tetraplegie"),
                                ),
                            ),
                            (
                                "Cognitieve / neurologische beperkingen",
                                (
                                    ("ADHD", "ADHD"),
                                    ("Autisme", "Autisme"),
                                    ("Leerstoornis", "Leerstoornis"),
                                    ("Geheugen beperking", "Geheugen beperking"),
                                    ("Multiple Sclerose", "Multiple Sclerose"),
                                    ("Epilepsie", "Epilepsie"),
                                    ("Migraine", "Migraine"),
                                ),
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research",
            },
        ),
    ]
