# Generated by Django 4.2.9 on 2024-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_research"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="status",
            field=models.CharField(
                choices=[
                    ("nieuw", "nieuw"),
                    ("goedgekeurd", "goedgekeurd"),
                    ("afgekeurd", "afgekeurd"),
                    ("gesloten", "gesloten"),
                ],
                default="nieuw",
                max_length=255,
            ),
        ),
    ]
