# Generated by Django 4.2.9 on 2024-03-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("experience_expert", "0002_experienceexpert_status"),
        ("organization", "0004_alter_research_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="ervaringsdeskundige",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="experience_expert.experienceexpert",
            ),
        ),
    ]
