# Generated by Django 4.2.9 on 2024-03-11 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_alter_research_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("goedgekeurd", "goedgekeurd"),
                    ("afgekeurd", "afgekeurd"),
                    ("in_behandeling", "in_behandeling"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
