# Generated by Django 4.2.9 on 2024-03-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("experience_expert", "0003_alter_experienceexpert_email"),
        ("organization", "0005_research_ervaringsdeskundige"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="ervaringsdeskundige",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="experience_expert.experienceexpert",
                to_field="email",
            ),
        ),
    ]
