# Generated by Django 4.2.9 on 2024-03-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_organization_status"),
        ("organization", "0006_alter_research_ervaringsdeskundige"),
    ]

    operations = []
