version: '3.9'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/accessibility_hub .
      - database:/accessibility_hub/database
    ports:
      - "8000:8000"

volumes:
  database: