# Generated by Django 4.2.9 on 2024-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience_expert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experienceexpert",
            name="status",
            field=models.CharField(
                choices=[
                    ("goedgekeurd", "goedgekeurd"),
                    ("afgekeurd", "afgekeurd"),
                    ("in_behandeling", "in_behandeling"),
                ],
                default="in_behandeling",
                max_length=50,
            ),
        ),
    ]
