# Generated by Django 4.2.9 on 2024-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience_expert", "0003_alter_experienceexpert_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceexpert",
            name="email_voogd_toezichthouder",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="experienceexpert",
            name="naam_voogd_toezichthouder",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="experienceexpert",
            name="tel_voogd_toezichthouder",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
